//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class 客戶資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "客戶名稱必填喔!! 啾咪>.^")]   
        public string 客戶名稱 { get; set; }
        [Required(ErrorMessage = "統一編號必填喔!! 啾咪>.^")]
        public string 統一編號 { get; set; }
        [Required(ErrorMessage = "電話必填喔!! 啾咪>.^")]
        public string 電話 { get; set; }
        [Required(ErrorMessage = "傳真必填喔!! 啾咪>.^")]
        public string 傳真 { get; set; }
        [Required(ErrorMessage = "地址必填喔!! 啾咪>.^")]
        public string 地址 { get; set; }
        [Required(ErrorMessage = "Email必填喔!! 啾咪>.^")]
        //[RegularExpression(@"[a-zA-Z0-9_]+@[a-zA-Z0-9\._]+", ErrorMessage = "請輸入符合格式的Email")]
        [EmailAddress(ErrorMessage="請輸入符合格式的Email")]
        [Remote("doesMailExist", "Validation", ErrorMessage = "Email already exists!")]
        public string Email { get; set; }
        public bool 是否已刪除 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
     
        
    }
}
