//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "客戶Id必填喔!! 啾咪>.^")]        
        public int 客戶Id { get; set; }
        [Required(ErrorMessage = "職稱必填喔!! 啾咪>.^")]
        public string 職稱 { get; set; }
        [Required(ErrorMessage = "姓名必填喔!! 啾咪>.^")]
        public string 姓名 { get; set; }
        [Required(ErrorMessage = "Email必填喔!! 啾咪>.^")]
        [RegularExpression(@"[a-zA-Z0-9_]+@[a-zA-Z0-9\._]+", ErrorMessage = "請輸入符合格式的Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "手機必填喔!! 啾咪>.^")]
        [RegularExpression(@"\d{4}-\d{6}",ErrorMessage="請輸入符合格式的手機號碼")]
        public string 手機 { get; set; }
        [Required(ErrorMessage = "電話必填喔!! 啾咪>.^")]
        public string 電話 { get; set; }
        public Nullable<bool> 是否已刪除 { get; set; }
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
